name: farmers
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          pip install dvc
          dvc repro
          
          git fetch --prune
          dvc metrics diff --show-md main

          # Add figure to the report
          echo "## Validating results by region"
          cml-publish by-region.png --md >> report.md
          cml-send-comment report.md